[build]
target = "index.html"
dist = "dist"
release = false
public_url = "/yew-ghpage/"            # for {username}.github.io/{project_name}
# public_url = "/<project_name>/"            # for {username}.github.io/{project_name}

[watch]
watch = [
    "./index.html",
    "src/",
    # "css/",
    "static/",
]

[clean]
dist = "dist"

# for tailwind
# [[hooks]]
# stage = "pre_build"
# command = "sh"
# # run tailwind build with webpack
# command_arguments = [
#     "-c",
#     "[ ! -d \"./node_modules\" ] && npm i || :; npm run build_css",
# ]